"""Extract complete source definitions for incremental linkage; never reads PE bytes.

The imported full client remains the editing source. This batch intentionally does
not build constructors/destructors or pretend that its capsule is a game client.
"""
import json,re
from pathlib import Path
from verify import ROOT
from binary import need


def definition(source,name):
    # Strip comments/string contents only for brace tracking, preserving positions.
    lexical=re.sub(r'//[^\r\n]*|/\*[\s\S]*?\*/|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'',
                   lambda m:' '*(m.end()-m.start()),source)
    pattern=r'(?m)^[^\r\n;{}]*\b'+re.escape(name)+r'\s*\([^;{}]*\)\s*\{'
    matches=list(re.finditer(pattern,lexical));need(len(matches)==1,'ambiguous source definition '+name)
    start=matches[0].start();at=matches[0].end();depth=1
    while depth and at<len(lexical):
        depth+=(lexical[at]=='{')-(lexical[at]=='}');at+=1
    need(depth==0,'unbalanced source definition')
    return source[start:at]


def prepare():
    c=json.loads((ROOT/'config/checkpoint32/regions.json').read_text())
    out=ROOT/'client/matching';out.mkdir(exist_ok=True)
    for unit in sorted({r['unit'] for r in c['regions']}):
        original=ROOT/'client/saco'/Path(unit.replace('_','/',1)+'.cpp')
        source=original.read_bytes().decode('latin1')
        definitions=[]
        for r in c['regions']:
            if r['unit']!=unit:continue
            fields=r['symbol'].split('@');name=fields[0][1:]
            if r['symbol'].startswith('??0'):
                cls=fields[0][3:];name=cls+'::'+cls
            elif fields[1]:name=fields[1]+'::'+name
            definitions.append(definition(source,name))
        text='// Generated by tools/prepare_checkpoint32.py from complete source definitions.\n'
        text+='#include "../saco/main.h"\n#include "../saco/game/util.h"\n\n'
        text+='\n\n'.join(definitions)+'\n'
        (out/(unit+'.cpp')).write_bytes(text.encode('latin1'))

if __name__=='__main__':prepare()
